# Deploy on builds from master and semantic versioned tags, e.g., v0.1.3
branches:
  only:
  - master
  - "/^v[0-9].*$/"

# Use python and tell it to use a particular version
language: python

python:
- '3.7'

# Install dependencies
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements.txt

# Make a database available. Be sure to update the version, if needed. (Optional.)
addons:
  postgresql: '9.4'

script: airflow initdb
