version: 0.0
os: linux
files:
 - source: /
   destination: /home/datamade/la-metro-dashboard-deployment-root
hooks:
  ApplicationStop:
  - location: scripts/app_stop.sh
    runas: root
  BeforeInstall:
  - location: scripts/before_install.sh
    runas: root
  ApplicationStart:
  - location: scripts/app_start.sh
    runas: root
  AfterInstall:
  - location: scripts/after_install.sh
    runas: root
branch_config:
  master:
    deploymentGroupName: staging
  deploy:
    deploymentGroupName: production
